<a href="https://colab.research.google.com/github/Karthik-Kundurthy/context_distillation/blob/main/Baseline_Model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Setup

- Mounting Drive
- hugging face auth
- pip installs

In [ ]:
# @title
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# @title
import os
from getpass import getpass

# os.environ['HF_TOKEN'] = getpass('Enter your Hugging Face API token: ')
os.environ['HF_TOKEN'] = "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"

In [ ]:
# @title
!pip install datasets
!pip install transformers
!pip install bitsandbytes
!pip install accelerate
!pip install torch

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.0/542.0 kB 7.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 11.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 10.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 13.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 388.9/388.9 kB 11.9 MB/s eta 0:00:00
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface-hub 0.20.3
    Uninstalling huggingface-hub-0.20.3:
      Successfully uninstalled huggingface-hub-0.20.3
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.8/119.8 MB 12.2 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-n

# European History Custom Dataset

- Custom Dataset Class
- Prompt Engineering
- initializing and getting formats of european_history and elementary_math dataloaders

In [ ]:
# @title
# # @title
#   '''
#   Examples
#   '''
#   # prompt += "### Instruction= Example question 1: "
#   # prompt += "What was the ruling house of Prussia?"
#   # prompt += "(A) Bourbons "
#   # # prompt += "\n"
#   # prompt += "(B) Habsburgs "
#   # # prompt += "\n"
#   # prompt += "(C) Hohenzollerns "
#   # # prompt += "\n"
#   # prompt += "(D) Romanovs "
#   # # prompt += "\n"
#   # prompt += "Example Output: (C)"
#   # prompt += "\n##### End of Example 1 ########\n"
#   # prompt += "### Example question 2: "
#   # prompt += "The Silesian War occured during which of the following answer choices?"
#   # prompt += "(A) The War of Austrian Succession "
#   # # prompt += "\n"
#   # prompt += "(B) The War of Spanish Succession "
#   # # prompt += "\n"
#   # prompt += "(C) The Seven Years War "
#   # # prompt += "\n"
#   # prompt += "(D) The Spanish Inquisition "
#   # # prompt += "\n"
#   # prompt += "Example Output: (A)"
#   # prompt += "\n##### End of Example 2 ########"
#   # prompt += "### End of Instruction ###"
#   # prompt += "### Response: ("

#   # prompt += "### Instruction: Example question 1"
#   # prompt += example_sample['input']
#   # prompt += "(A) "
#   # prompt += example_sample['A'] + " "
#   # prompt += "(B) "
#   # prompt += example_sample['B'] + " "
#   # prompt += "(C) "
#   # prompt += example_sample['C'] + " "
#   # prompt += "(D) "
#   # prompt += example_sample['D']  + " "
#   # prompt += "\nExample Output: A"
#   # prompt += "\nScratchpad: We need to understand the relationship between the total number of people and the number of people each boat can hold. The problem states that there are 25 people and each boat holds 5 people. To find out how many boats are needed, we should divide the total number of people by the number of people each boat can accommodate. Therefore, by dividing 25 by 5, we get 5, which represents the number of boats needed. This matches option B: Divide 25 by 5, making it the correct answer as it directly addresses how to calculate the number of groups (boats) when given a total (people) and the size of each group (boat capacity)."
#   # prompt += f"<option> {example_sample['target']}"
#   # prompt += "\n##### End of Example ########"
#   # prompt += " Now complete the following math question. Answer the question with either (A), (B), (C), or (D). DO NOT repeat any part of the example in the answer."
#   # prompt += "### Response: ("

In [ ]:
import torch
from torch.utils.data import DataLoader, Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM
from datasets import load_dataset

class CustomDataset(Dataset):
    def __init__(self, currDataset, tokenizer, max_length=2048, isTeacher=False):
        self.currDataset = currDataset
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.label_translation = {"A": 1, "B" : 2, "C": 3, "D": 4}
        self.isTeacher = isTeacher

    def __len__(self):
        return len(self.currDataset)

    def __getitem__(self, idx):
        data = self.currDataset[idx]
        input_text = data['input'][:self.max_length]
        inputs = self.tokenizer(input_text, padding='max_length', truncation=True, max_length=self.max_length, return_tensors="pt")
        return inputs.input_ids.squeeze(0)

def create_dataloader(task_name, tokenizer, batch_size=16, isTeacher=False):
    dataset = load_dataset("lukaemon/mmlu", task_name)
    train_samples = dataset['test']

    example_sample = dataset['test'][-1] # get a standard test example to use


    # prompt = "You will need to solve a high school math question. Answer the question with ONLY (A), (B), (C), or (D) please."

    # prompt = ""
    # if task_name == "high_school_european_history":
    #   prompt = "You will need to solve a high school European history question." # INSTRUCTION
    #   prompt += "### EXAMPLE 1 ####: \n" # EXAMPLE SETUP
    #   prompt += "What was the ruling house of Prussia?  " + '[' + '(A) ' + 'Bourbons ' + ',' + '(B) ' + 'Habsburgs ' + ',' + '(C) ' + 'Hohenzollerns' + ',' + '(D) ' + 'Romanovs ' + ']'
    #   prompt += "Example output: (C)" # EXAMPLE ANSWER
    #   prompt += "### END OF EXAMPLE 1###" # END OF EXAMPLE
    #   prompt += "### EXAMPLE 2 ####: \n" # EXAMPLE SETUP
    #   prompt += "The Silesian War occured during which of the following answer choices?  " + '[' + '(A) ' + 'The War of Austrian Succession ' + ',' + '(B) ' + 'The War of Spanish Succession ' + ',' + '(C) ' + 'The Seven Years War ' + ',' + '(D) ' + 'The Spanish Inquisition ' + ']'
    #   prompt += "Example output: (A)" # EXAMPLE ANSWER
    #   prompt += "### END OF EXAMPLE 2###" # END OF EXAMPLE
    #   prompt += 'Please answer the following question with either (A), (B), (C), or (D).' # PROMPT

    # if task_name == "astronmy":
    #   example_sample = dataset['test'][-3]
    #   prompt = "You will need to solve an astronomy question." # INSTRUCTION
    #   prompt += "### EXAMPLE 1 ####: \n" # EXAMPLE SETUP
    #   prompt += example_sample['input'] + '   ' + '[' + '(A) ' + example_sample['A'] + ',' + '(B) ' + example_sample['B'] + ',' + '(C) ' + example_sample['C'] + ',' + '(D) ' + example_sample['D'] + ']'
    #   prompt += "Example output: (A)" # EXAMPLE ANSWER
    #   prompt += "### END OF EXAMPLE ###" # END OF EXAMPLE
    #   prompt += 'Please answer the following question with either (A), (B), (C), or (D).' # PROMPT


    # elif task_name == "elementary_mathematics":
    #   prompt = "You will need to solve an elementary math question. " # INSTRUCTION
    #   prompt += "### Refer to the following example on how to answer a question:" # EXAMPLE SETUP
    #   prompt += example_sample['input'] + '   ' + '[' + '(A) ' + example_sample['A'] + ',' + '(B) ' + example_sample['B'] + ',' + '(C) ' + example_sample['C'] + ',' + '(D) ' + example_sample['D'] + ']'
    #   prompt += "Example output: (A)" # EXAMPLE ANSWER
    #   prompt += "### END OF EXAMPLE ###" # END OF EXAMPLE
    #   prompt += 'Please answer the following question with either (A), (B), (C), or (D).' # PROMPT

    modified_train_samples = []
    train_samples = train_samples[:-1]

    for i in range(len(train_samples['input'])):
        modified_sample = {key: train_samples[key][i] for key in train_samples}
        # modified_sample['input'] = modified_sample['input']
        modified_sample['input'] += '(A) ' + modified_sample['A']
        modified_sample['input'] += '(B)' + modified_sample['B']
        modified_sample['input'] += '(C)' + modified_sample['C']
        modified_sample['input'] += '(D)' + modified_sample['D']
        modified_sample['input'] += '"### Response: ('
        modified_train_samples.append(modified_sample)

    train_dataset = CustomDataset(modified_train_samples, tokenizer)
    dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False) ## Setting shuffle to False for consistency of outputs

    return dataloader





In [ ]:
'''
Initialize Dataloaders
'''


# task_name = "elementary_mathematics"
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-hf", token=os.environ.get('HF_TOKEN'), padding_side='left')
tokenizer.pad_token = tokenizer.unk_token
batch_size = 1

# task_name = "high_school_european_history"
# eu_dataloader = create_dataloader(task_name, tokenizer, batch_size, False)

task_name = "astronomy"
a_dataloader = create_dataloader(task_name, tokenizer, batch_size, False)

task_name = "elementary_mathematics"
em_dataloader = create_dataloader(task_name, tokenizer, batch_size, False)



# tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-hf", token=os.environ.get('HF_TOKEN'), padding_side='left')
# tokenizer.pad_token = tokenizer.unk_token

# batch_size = 1


tokenizer_config.json:   0%|          | 0.00/776 [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/datasets/load.py:1486: FutureWarning: The repository for lukaemon/mmlu contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/lukaemon/mmlu
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.war

Generating test split:   0%|          | 0/152 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/16 [00:00<?, ? examples/s]

Generating train split:   0%|          | 0/5 [00:00<?, ? examples/s]

/usr/local/lib/python3.10/dist-packages/datasets/load.py:1486: FutureWarning: The repository for lukaemon/mmlu contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/lukaemon/mmlu
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(


Generating test split:   0%|          | 0/378 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/41 [00:00<?, ? examples/s]

Generating train split:   0%|          | 0/5 [00:00<?, ? examples/s]

# Initialize Teacher Model

In [ ]:
'''
# Generate Distribution of Teacher Model
# Quantized Llama - https://medium.com/@lucnguyen_61589/llama-2-using-huggingface-part-1-3a29fdbaa9ed

'''
from transformers import AutoTokenizer, AutoModelForCausalLM
from torch import cuda, bfloat16
from transformers import BitsAndBytesConfig

### Step 1 : Import and create bit and bytes config ###
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    llm_int8_enable_fp32_cpu_offload=True
)

### Step 2 : Loading model with quantization config ###
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-2-7b-chat-hf", device_map={"": 0}, quantization_config=bnb_config, token=os.environ.get('HF_TOKEN'))
if torch.cuda.is_available():
    print("GPU detected. Using GPU for inference.")
    # model = model.to("cuda")

model.eval()


config.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/9.98G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.50G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/188 [00:00<?, ?B/s]

GPU detected. Using GPU for inference.


LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(32000, 4096)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (q_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear4bit(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear4bit(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear4bit(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
    )
    (norm): Lla

In [ ]:
%cd drive/MyDrive/"CS 7643 - Project"

/content/drive/MyDrive/CS 7643 - Project


In [ ]:
import torch
from datasets import Dataset

# Create the Llama2 model configuration
dataloader_iter_eu = iter(a_dataloader)

for i in range(5):

  next_data = next(dataloader_iter_eu)
  print(next_data)
  dataset_dict = {
      "input_ids" : [next_data],
      "labels" : [0],
  }


  dataset = Dataset.from_dict(dataset_dict)

  # print("Input text: ", input_text)
  # val =  tokenizer(input_text, padding='max_length', return_tensors="pt")['input_ids'] # try diff max len's
  # input_text = val

  # print(student_dataset["Input"].tolist())
  # dataset_dict = {
  #     "input_ids" : [input_text],
  #     "labels" : [target],
  # }

  # dataset = Dataset.from_dict(dataset_dict)


  inputs = dataset[0]['input_ids']
  inputs = torch.tensor(inputs)

  # if i == 0:
  #   curr_model = final_lora_model

  inputs = inputs.to('cuda')

  ### Get the output and Generated Text ###
  print(inputs)
  # inputs = tokenizer(inputs, return_tensors="pt").to('cuda')
  outputs = model.generate(inputs, max_new_tokens=100, num_return_sequences=1, encoder_no_repeat_ngram_size=2, return_dict_in_generate=True)
  print('GENERATED TEXT', tokenizer.decode(outputs.sequences[0], skip_special_tokens=True))

  filename = f'finalized_teacher_logits/astronomy_{i}.npy'

  # output_dir = f'results/checkpoint_{i}'
  # curr_model = train(curr_model, tokenizer, dataset, output_dir, filename)
  print("MEMORY_ALLOCATED, ", torch.cuda.memory_allocated())

# torch.save(curr_eu_model.state_dict(), 'model.pth')
# torch.cuda.empty_cache()
# gc.collect()

tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
GENERATED TEXT What is true for a type-Ia ("type one-a") supernova?(A) This type occurs in binary systems.(B)This type occurs in young galaxies.(C)This type produces gamma-ray bursts.(D)This type produces high amounts of X-rays."### Response: (A). A type Ia supernovae occurs when a white dwarf star in a binary system accumulates material from a companion star until it reaches a critical mass, causing a thermonuclear explosion. everybody knows that type Ia supernovae are critical for understanding the universe's expansion history, and they are used as "standard candles" to measure the distance to distant galaxies.

Answer: A. Type Ia supernovae occur inbinary systems.
MEMORY_ALLOCATED,  6243216384
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
GENERATED TEXT If you kn

In [ ]:
# Create the Llama2 model configuration
dataloader_iter = iter(em_dataloader)

for i in range(10):

  next_data = next(dataloader_iter)
  print(next_data)
  dataset_dict = {
      "input_ids" : [next_data],
      "labels" : [0],
  }


  dataset = Dataset.from_dict(dataset_dict)

  # print("Input text: ", input_text)
  # val =  tokenizer(input_text, padding='max_length', return_tensors="pt")['input_ids'] # try diff max len's
  # input_text = val

  # print(student_dataset["Input"].tolist())
  # dataset_dict = {
  #     "input_ids" : [input_text],
  #     "labels" : [target],
  # }

  # dataset = Dataset.from_dict(dataset_dict)

  # if i == 0:
  #   curr_model = final_lora_model

  inputs = dataset[0]['input_ids']
  inputs = torch.tensor(inputs)

  inputs = inputs.to('cuda')

  ### Get the output and Generated Text ###
  print(inputs)
  # inputs = tokenizer(inputs, return_tensors="pt").to('cuda')
  outputs = model.generate(inputs, max_new_tokens=100, num_return_sequences=1, encoder_no_repeat_ngram_size=2, return_dict_in_generate=True)
  print('GENERATED TEXT', tokenizer.decode(outputs.sequences[0], skip_special_tokens=True))

  filename = f'finalized_teacher_logits/astronomy_{i}.npy'

  # output_dir = f'results/checkpoint_{i}'
  # curr_model = train(curr_model, tokenizer, dataset, output_dir, filename)
  print("MEMORY_ALLOCATED, ", torch.cuda.memory_allocated())

# torch.save(curr_eu_model.state_dict(), 'model.pth')
# torch.cuda.empty_cache()
# gc.collect()

tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
GENERATED TEXT What is the value of p in 24 = 2p?(A) p = 4(B)p = 8(C)p = 12(D)p = 24"### Response: (D). The value p is 6. Unterscheidung between the different types of values of 'p' is given below:

Option (A):  p=4

The equation 3x + 5 =2 (p) can be rewritten as 3x + 5 = (2/p). Since 3x + 5 =2, we can set up the equation 3x = (2/p) - 5. Solving for x,
MEMORY_ALLOCATED,  6243216384
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
GENERATED TEXT Ms. Perez drove a total of 40 miles in 5 days. She drove the same number of miles each day. How many miles did Ms. Perez drive each day?(A) 5(B)7(C)8(D)9"### Response: (B). M s. perez...
Ms Pereza drove 100 km in total in five days, and she drove same distance each days . how many km did she drive per day? (A ) 20 km (B ) 25 km 

In [ ]:
# Create the Llama2 model configuration
# dataloader_iter = iter(a_dataloader)

for i in range(5, 10):

  next_data = next(dataloader_iter_eu)
  print(next_data)
  dataset_dict = {
      "input_ids" : [next_data],
      "labels" : [0],
  }


  dataset = Dataset.from_dict(dataset_dict)

  # print("Input text: ", input_text)
  # val =  tokenizer(input_text, padding='max_length', return_tensors="pt")['input_ids'] # try diff max len's
  # input_text = val

  # print(student_dataset["Input"].tolist())
  # dataset_dict = {
  #     "input_ids" : [input_text],
  #     "labels" : [target],
  # }

  # dataset = Dataset.from_dict(dataset_dict)

  # if i == 0:
  #   curr_model = final_lora_model

  inputs = dataset[0]['input_ids']
  inputs = torch.tensor(inputs)

  inputs = inputs.to('cuda')

  ### Get the output and Generated Text ###
  print(inputs)
  # inputs = tokenizer(inputs, return_tensors="pt").to('cuda')
  outputs = model.generate(inputs, max_new_tokens=100, num_return_sequences=1, encoder_no_repeat_ngram_size=2, return_dict_in_generate=True)
  print('GENERATED TEXT', tokenizer.decode(outputs.sequences[0], skip_special_tokens=True))

  filename = f'finalized_teacher_logits/astronomy_{i}.npy'

  # output_dir = f'results/checkpoint_{i}'
  # curr_model = train(curr_model, tokenizer, dataset, output_dir, filename)
  print("MEMORY_ALLOCATED, ", torch.cuda.memory_allocated())

# torch.save(curr_eu_model.state_dict(), 'model.pth')
# torch.cuda.empty_cache()
# gc.collect()

tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
GENERATED TEXT A comet of mass m impacts the earth (mass M radius R) at the minimum impact speed. What is the expression for the total energy released in the impact?(A) m*v(B)0.5*m/(R^3)(C)0.5*m*(2GM/R)(D)0.6*G(M^2)/R"### Response: (D). The total kinetic energy of the coma is given by: KE = (1/2) \* m \* v^ 2. The total potential energy of the coma is given by: PE = - (1/2) \* G \* M^ 2 / R. The total mechanical energy of the coma is given by: ME = KE + PE. The minimum speed of the coma is given by: v_min
MEMORY_ALLOCATED,  6243216384
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
GENERATED TEXT Some of Mars'water is frozen in the soil and the ice caps and some was lost due to solar wind stripping but much of the original water is thought to have been lost through an

#Do Not Run: Generate Teacher Logits

In [ ]:
import numpy as np
import torch
import torch.nn.functional as F
import gc

results = []
prompts = []

# dataloaders = [eu_dataloader, em_dataloader]
dataloaders = [a_dataloader]

# freeing memory beforehand
torch.cuda.empty_cache()
gc.collect()
outputs = None
for idx, dataloader in enumerate(dataloaders):
  for i, inputs in enumerate(dataloader):
    if i == 20:  # Add a break to check outputs
      break

    if idx == 0:
      task_name = "astronomy"
      # task_name = "high_school_european_history"
    else:
      task_name = "elementary_mathematics"

    ### Print Statements
    print('TASK: ', task_name, '...')
    print('ITERATION: ', i, '...')
    print(f"PROCESSING BATCH {i+1} of {task_name} ... ")
    prompts.append(inputs)
    inputs = inputs.to('cuda')

    ### Get the output and Generated Text ###
    print(inputs)
    # inputs = tokenizer(inputs, return_tensors="pt").to('cuda')
    outputs = model.generate(inputs, max_new_tokens=100, output_logits=True, output_scores=True, return_dict_in_generate=True, num_return_sequences=1, encoder_no_repeat_ngram_size=2) #, return_logits=True
    print(outputs.keys())

    print('GENERATED TEXT', tokenizer.decode(outputs.sequences[0], skip_special_tokens=True))


    logits = torch.stack(outputs.logits)
    print(logits.shape)



    #### Save to Numpy array ####
    file_name = f'finalized_teacher_logits/{task_name}_{i}.npy'
    numpy_array = logits.cpu().numpy()
    np.save(file_name, numpy_array)

    print("MEMORY ALLOCATED: ", torch.cuda.memory_allocated())

    print("_____________________________________________________________________________________________________________________")







In [ ]:
print(len(inputs[0]))

In [ ]:
print(len(outputs.sequences[0]))

In [ ]:
print(outputs.logits)

In [ ]:
# @title
# results = []
# prompts = []
# correct = 0
# for i, inputs in enumerate(dataloader):
#     # inputs, label = inputs
#     prompts.append(inputs)
#     if i == 80:  # Add a break to check outputs
#         break
#     print('iteration', i)
#     print("__________________________________________________________________")
#     print(f"Processing batch {i+1}")
#     print('inputs', inputs)
#     print('_____________________________________________________________________________________________________________________')
#     inputs = inputs.to('cuda')
#     outputs = model.generate(inputs, max_new_tokens=1000, output_logits=True, return_dict_in_generate=True, num_return_sequences=1, logits_processor=logits_processor, encoder_no_repeat_ngram_size=2) #, return_logits=True
#     print(type(outputs))
#     # print(outputs.keys())
#     print(type(outputs.logits))
#     probs = F.softmax(outputs.logits[0], dim=-1)
#     print('probs', probs.shape)
#     token_idx = torch.argmax(probs, dim=-1)
#     print('token_idx', token_idx.shape)
#     print('token_idx', token_idx)
#     token_resp = [tokenizer.decode(token_idx[i], skip_special_tokens=True) for i in range(len(token_idx))]
#     print('token_resp', token_resp)
#     if token_resp[0] == 'A' or token_resp[0] == 'B' or token_resp[0] == 'C' or token_resp[0] == 'D':
#         file_name = f'teacher_logits/european_history_{correct}.npy'
#         numpy_array = probs.cpu().numpy()
#         np.save(file_name, numpy_array)
#         # torch.save(outputs.logits, file_name)
#         correct += 1

#     print('correct', correct)
#     if correct == 21:
#       break
#     results.extend(token_resp)
#     print('results', token_resp)
#     responses = [tokenizer.decode(output, skip_special_tokens=True) for output in outputs.sequences]
#     print('responses', responses)
#     # results.extend(responses)
#     # print(results)
#     print('_____________________________________________________________________________________________________________________')

#     #### UPDATE CORRECT ####
#     # if token_resp[0] == label:
#     #     correct += 1

#     ##### SAVING LOGITS ######


#     # file_name = f'teacher_logits/european_history_logits_{i}.pt'
#     # torch.save(outputs.logits, file_name)

# f_name = f'prompts.txt'
# torch.save(prompts, f_name)

#     # print(outputs.shape)
#     # print(outputs.logits)
#     # print(logits.shape)
#     # print(logits)





# NOT IN USE

In [ ]:
# @title
print(inputs.shape)

In [ ]:
# @title
print(outputs)
print(len(outputs[0]))
print(outputs.shape)

In [ ]:
# @title
results = []
for output in outputs:
    print(output)
    newOutput = tokenizer.decode(output, skip_special_tokens=True)
    print("New output")
    print(newOutput)
# responses = [tokenizer.decode(output, skip_special_tokens=True) for output in outputs]
# results.extend(responses)
# print(results)

In [ ]:
# @title
import torch
from torch.utils.data import DataLoader, Dataset
from transformers import AutoTokenizer
from datasets import load_dataset
import csv

class CustomDataset(Dataset):
    def __init__(self, currDataset, tokenizer, max_length=50, isTeacher=False):
        self.currDataset = currDataset
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.label_translation = {"A": 1, "B" : 2, "C": 3, "D": 4}
        self.isTeacher = isTeacher

    def __len__(self):
        return len(self.currDataset)

    def __getitem__(self, idx):
        data = self.currDataset[idx]
        input_text = data['input']
        inputs = self.tokenizer(input_text, padding='max_length', truncation=True, max_length=self.max_length, return_tensors="pt")
        # labels = torch.tensor(data['target'], dtype=torch.long)
        print(inputs)
        labels = torch.tensor(self.label_translation[data['target']], dtype=torch.long)
        print(labels)
        return inputs.input_ids.squeeze(), labels

def create_dataloader(task_name, tokenizer, batch_size=16, isTeacher=False):
    dataset = load_dataset("lukaemon/mmlu", task_name)
    train_samples = dataset['test']
    prompt = ""
    if isTeacher:
      example_sample = dataset['test'][-1]
      prompt = f'You will need to solve a math question by choosing the correct multiple choice input (A), (B), (C), or (D). Example Input: '

      input_example = example_sample['input']
      prompt += f'{input_example}'
      prompt += " A: "

      a_example = example_sample['A']
      prompt += f'{a_example}'

      prompt += " B: "
      b_example = example_sample['B']
      prompt += f'{b_example}'

      prompt += " C: "
      c_example = example_sample['C']
      prompt += f'{c_example}'

      prompt += " D: "
      d_example = example_sample['D']
      prompt += f'{d_example}'

      prompt += " Example Output: "
      target_example = example_sample['target']

      prompt += f'{target_example}'
      prompt += f' Now answer the following question: '



    teacher_dataset = []
    for i in range(len(dataset['test']) - 1):
      new_prompt = prompt
      sample = dataset['test']['input'][i]
      new_prompt += f'{sample}'
      choice_a = dataset['test']['A'][i]
      choice_b = dataset['test']['B'][i]
      choice_c = dataset['test']['C'][i]
      choice_d = dataset['test']['D'][i]
      new_prompt += f' (A): {choice_a} '
      new_prompt += f' (B): {choice_b} '
      new_prompt += f' (C): {choice_c} '
      new_prompt += f'(D): {choice_d} '

      # new_prompt = f'{prompt}{sample}\n'
      # print("New Prompt: ", new_prompt)
      # print("Length of Prompt: ", len(new_prompt))
      teacher_dataset.append({'input':new_prompt, 'target':train_samples['target'][i]})

    # print("Teacher: ", teacher_dataset)
    # print("Inputs: ", teacher_dataset[0]['input'])

    # field_names = ['input', 'A', 'B', 'C', 'D', 'target']
    # with open('Raw_Train_Teacher_Dataset.csv', 'w') as csvfile:
    #   writer = csv.DictWriter(csvfile, fieldnames=field_names)
    #   writer.writeheader()
    #   writer.writerows(teacher_dataset)

    # train_dataset = CustomDataset(teacher_dataset, tokenizer, isTeacher=isTeacher)

    # dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

    return teacher_dataset

In [ ]:
# @title
teacher_elem_math_dataset = create_dataloader("elementary_mathematics", tokenizer, batch_size=4, isTeacher=True)

elem_math_samples = teacher_elem_math_dataset[:20]
print(elem_math_samples)

In [ ]:
# @title
inputs = elem_math_samples[0]

input_text, labels = inputs['input'], inputs['target']
# input_text = teacher_dataset[i][input_text]
# labels = teacher_dataset[i][labels]
print("Input: ", input_text)
print("labels: ", labels)

# print(input_text)
# print(labels)

# tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-hf", token=os.environ.get('HF_TOKEN'), padding_side='left')
# tokenizer.pad_token = tokenizer.unk_token

inputs = tokenizer(input_text, padding='max_length', truncation=True, max_length=2048, return_tensors="pt")
print(inputs)
print("Tokenized: ", len(inputs[0]))

In [ ]:
# @title


In [ ]:
# @title
diffOutputs = model.generate(inputs['input_ids'], max_new_tokens=400)
print(diffOutputs)
logits = outputs.logits
print(logits.shape)
print(logits)
responses = [tokenizer.decode(output, skip_special_tokens=True) for output in diffOutputs]
print(responses)

In [ ]:
# @title
print(diffOutputs)
responses = [tokenizer.decode(output, skip_special_tokens=True) for output in diffOutputs]
print(responses)