<a href="https://colab.research.google.com/github/Karthik-Kundurthy/context_distillation/blob/main/Context_Distillation_Final_Llama.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



# Setup

pip install, mount drive, hugging face token



In [ ]:
# @title
!pip install peft
!pip install datasets
!pip install datasets
!pip install transformers
!pip install bitsandbytes
!pip install accelerate
!pip install torch

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.1/199.1 kB 5.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 297.6/297.6 kB 28.9 MB/s eta 0:00:00
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (23.7 MB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (823 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl (14.1 MB)
  Using cached nvidia_cudnn_cu12-8.9.2.26-py3-none-manylinux1_x86_64.whl (731.7 MB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl (410.6 MB)
  Using cached nvidia_cufft_cu12-11.0.2.54-py3-none-manylinux1_x86_64.whl (121.6 MB)
  Using cached nvidia_curand_cu12-10.3.2.106-py3-none-manylinux1_x86_64.whl (56.5 MB)
  Using cached nvidia_cusolver_cu12-11.4.5.107-py3-none-manylinux1_x86_64.whl (124.2 MB)
  Using cached nvidia_cusparse_cu12-12.1.0.106-py3-none-manylinux1_x86_64.whl (196.0 MB)
  Using cached nvidia_nccl_cu12-2.19.3-py3-none-many

In [ ]:
# @title
from google.colab import drive
drive.mount('/content/drive')
%cd '/content/drive/.shortcut-targets-by-id/1Lb1kmegrlLW6PSJzuwWZ1N1kYDI5y7U3/CS 7643 - Project'

Mounted at /content/drive
/content/drive/.shortcut-targets-by-id/1Lb1kmegrlLW6PSJzuwWZ1N1kYDI5y7U3/CS 7643 - Project


In [ ]:
# @title
import os
os.environ['HF_TOKEN'] = "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"

# Quantized Model

- Preemptively free memory
- Generate Distribution of Teacher Model
- Quantized Llama - https://medium.com/@lucnguyen_61589/llama-2-using-huggingface-part-1-3a29fdbaa9ed
- Quantized Llora

**Key Challenge: Memory Efficient Model Representation**




In [ ]:
'''
FREE MEMORY
'''

import torch
import gc

# freeing memory beforehand
torch.cuda.empty_cache()
gc.collect()

0

In [ ]:
# @title

'''
BITS AND BYTES CONFIG
'''
import os
from transformers import AutoTokenizer, AutoModelForCausalLM
import torch
from torch import cuda, bfloat16
from transformers import BitsAndBytesConfig
import bitsandbytes as bnb


## Step 1 : Import and create bit and bytes config ###
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    llm_int8_enable_fp32_cpu_offload=True
)

### Step 2 : Loading model with quantization config ###
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-2-7b-chat-hf", device_map={"": 0}, quantization_config=bnb_config, token=os.environ.get('HF_TOKEN'))


config.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/9.98G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.50G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/188 [00:00<?, ?B/s]

In [ ]:
'''
Applying Quantized Llora
'''

from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer
from peft import prepare_model_for_kbit_training, PeftModel, LoraConfig, get_peft_model


# Enabling Gradient Checkpointing
model.gradient_checkpointing_enable()

# Prepare model for LoRA training
lora_model = prepare_model_for_kbit_training(model,use_gradient_checkpointing=True)

config = LoraConfig(
    r=1,  # rank of the adapters
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "lm_head"],  # layers to apply LoRA
    bias="none",
    lora_dropout=0.05,
    task_type="CAUSAL_LM"
)
print(config.inference_mode)
# config.inference_mode = True

final_lora_model = get_peft_model(lora_model, config)

False


# Trainable Parameters Info

In [ ]:
# @title
def print_trainable_parameters(model, use_4bit=False):
    """Prints the number of trainable parameters in the model."""
    trainable_params = 0
    all_param = 0
    for _, param in model.named_parameters():
        num_params = param.numel()
        # if using DS Zero 3 and the weights are initialized empty
        if num_params == 0 and hasattr(param, "ds_numel"):
            num_params = param.ds_numel
        all_param += num_params
        if param.requires_grad:
            trainable_params += num_params
    if use_4bit:
        trainable_params /= 2
    print(f"all params: {all_param:,} trainable params: {trainable_params:,} trainable%: {100 * trainable_params / all_param}")

In [ ]:
print_trainable_parameters(final_lora_model, use_4bit=True)

all params: 3,501,497,600 trainable params: 542,336.0 trainable%: 0.015488686897857647


# Tokenizer

In [ ]:

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-chat-hf", token='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', padding_side='left')
tokenizer.pad_token = tokenizer.unk_token

tokenizer_config.json:   0%|          | 0.00/1.62k [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

# Trainer

https://towardsdatascience.com/qlora-how-to-fine-tune-an-llm-on-a-single-gpu-4e44d6b5be32

In [ ]:
import torch
from transformers import Trainer, TrainingArguments
import torch.nn.functional as F
from transformers import LogitsProcessorList, MinLengthLogitsProcessor, StoppingCriteriaList, MaxLengthCriteria
import numpy as np
import torch.nn as nn
from datasets import Dataset


# freeing memory beforehand
torch.cuda.empty_cache()
gc.collect()


# count = 0

# filename = f'teacher_logits/test_logits_2.npy'
# teacher_logits = np.load(filename)
# teacher_logits = torch.from_numpy(teacher_logits)
# teacher_top_k_probs, teacher_top_k_indices = torch.topk(teacher_logits, 50, dim=-1)
# teacher_normalized_probs = teacher_top_k_probs / torch.sum(teacher_top_k_probs, dim=-1, keepdim=True)
# teacher_normalized_probs = teacher_normalized_probs.to('cuda')

# Assuming the model and dataset are already defined
# print('......Set tokenizer.......')
# tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-chat-hf", token=os.environ.get('HF_TOKEN'))
# tokenizer.pad_token = tokenizer.unk_token

179

In [ ]:
# Modify training loop to use KL divergence loss
def train(model, tokenizer, dataset, output_dir, teacher_file):
    # Training parameters

    training_args = TrainingArguments(
        per_device_train_batch_size=1,
        per_device_eval_batch_size=1,
        gradient_accumulation_steps=1,
        # warmup_steps=2,
        max_steps=1,
        num_train_epochs=1,
        output_dir=output_dir,
        evaluation_strategy="no",
        gradient_checkpointing=True,
        # fp16=True,
        # load_best_model_at_end=True,
        # optim="paged_adamw_8bit", # "ingredient 3", paged optimizers,
        # do_train=True,
        # do_eval=False,
        # do_predict=False
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=dataset,
    )


    # trainer = SFTTrainer(
    #     model=model,
    #     args=training_args,
    #     train_dataset=dataset,
    #     peft_config=config,
    #     packing=False,
    #     dataset_text_field="text",
    #     dataset_labels_field="labels

    # )


    # Override the compute_loss method of the Trainer
    def compute_loss(model, inputs, return_outputs=False):
        # global count

        print(".....Computing Loss , Generating Outputs.........")
        softmax = nn.Softmax(dim=-1)

        # outputs = model.generate(model_in, max_new_tokens=5, output_logits=True, return_dict_in_generate=True, num_return_sequences=1, encoder_no_repeat_ngram_size=2) #, return_logits=True
        inputs.keys()
        input_text = tokenizer.decode(inputs['input_ids'][0][0].tolist(), skip_special_tokens=True)
        val = inputs['input_ids'][0]
        print("Val: ", val)


        print("Input Text: ", input_text)
        print(val)

        print(teacher_file)
        filename = teacher_file
        print(filename)
        teacher_logits = np.load(filename)
        teacher_logits = torch.from_numpy(teacher_logits)
        teacher_logits = teacher_logits.squeeze(1)
        print("Teacher: ", teacher_logits.shape)
        # print("Student: ", student_logits.shape)
        teacher_top_k_probs, teacher_top_k_indices = torch.topk(teacher_logits, 50, dim=-1)
        # teacher_normalized_probs = teacher_top_k_probs / torch.sum(teacher_top_k_probs, dim=-1, keepdim=True)
        # teacher_normalized_probs = teacher_normalized_probs.to('cuda')
        teacher_top_k_logits, _ = torch.topk(teacher_logits, 50, dim=-1)
        teacher_normalized_probs =  softmax(teacher_top_k_logits).to('cuda')

        student_prob_distributions = []
        for i in range(teacher_logits.shape[0] + 1):
          outputs = model(val)
          logits = outputs[0]

          last_logit = logits[:, -1, :]

          next_token_id = torch.argmax(last_logit, dim=-1).item()

          generated_text = tokenizer.decode(next_token_id, skip_special_tokens=True)
          input_text += generated_text

          val = tokenizer(input_text, return_tensors="pt")['input_ids']

          if i > 0:
            student_logits = softmax(last_logit.float())
            student_top_k_logits, _ = torch.topk(student_logits, 50, dim=-1)
            # student_normalized_probs = student_top_k_probs / torch.sum(student_top_k_probs, dim=-1, keepdim=True)
            # student_prob_distributions.append(student_normalized_probs[0])
            student_normalized_probs =  softmax(student_top_k_logits) #student_top_k_logits / torch.sum(student_top_k_logits, dim=-1, keepdim=True)
            student_prob_distributions.append(student_normalized_probs[0])

          if i % 50 == 0:
            print("Token: ", i)




        print("Generated Text:", input_text)
        print("_______________________________________")

        # student_logits = softmax(last_logit.float())
        # student_top_k_probs, _ = torch.topk(student_logits, 50, dim=-1)
        # student_normalized_probs = student_top_k_probs / torch.sum(student_top_k_probs, dim=-1, keepdim=True)
        # student_normalized_probs.requires_grad = True



        student_prob_distributions_tensor = torch.stack(student_prob_distributions).to('cuda')
        print(student_prob_distributions_tensor.shape)


        # count += 1

        kl_div = nn.KLDivLoss(reduction='batchmean')
        print("Teacher: ", teacher_normalized_probs.shape)
        print("Student: ", student_prob_distributions_tensor.shape)
        loss = - kl_div(student_prob_distributions_tensor, teacher_normalized_probs)
        print('loss', loss)

        # print(type(loss))
        # loss.requires_grad= True
        # loss.backward()

        return (loss, outputs) if return_outputs else loss



    trainer.compute_loss = compute_loss
    # print(len(trainer.train_dataset['input_ids']))
    # N = len(trainer.train_dataset['input_ids'])

    trainer.train()
    print("MEMORY ALLOCATED: ", torch.cuda.memory_allocated())
    return model

# Load Data

In [ ]:
import torch
from torch.utils.data import DataLoader, Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM
from datasets import load_dataset

class CustomDataset(Dataset):
    def __init__(self, currDataset, tokenizer, max_length=2048, isTeacher=False):
        self.currDataset = currDataset
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.label_translation = {"A": 1, "B" : 2, "C": 3, "D": 4}
        self.isTeacher = isTeacher

    def __len__(self):
        return len(self.currDataset)

    def __getitem__(self, idx):
        data = self.currDataset[idx]
        input_text = data['input'][:self.max_length]
        inputs = self.tokenizer(input_text, padding='max_length', truncation=True, max_length=self.max_length, return_tensors="pt")
        return inputs.input_ids.squeeze(0)

def create_dataloader(task_name, tokenizer, batch_size=16, isTeacher=False):
    dataset = load_dataset("lukaemon/mmlu", task_name)
    train_samples = dataset['test']

    example_sample = dataset['test'][-1] # get a standard test example to use
    prompt = ""


    # prompt = "You will need to solve a high school math question. Answer the question with ONLY (A), (B), (C), or (D) please."


    # if task_name == "high_school_european_history":
      # prompt = "You will need to solve a high school European history question." # INSTRUCTION
      # prompt += "### EXAMPLE 1 ####: \n" # EXAMPLE SETUP
      # prompt += "What was the ruling house of Prussia?  " + '[' + '(A) ' + 'Bourbons ' + ',' + '(B) ' + 'Habsburgs ' + ',' + '(C) ' + 'Hohenzollerns' + ',' + '(D) ' + 'Romanovs ' + ']'
      # prompt += "Example output: (C)" # EXAMPLE ANSWER
      # prompt += "### END OF EXAMPLE 1###" # END OF EXAMPLE
      # prompt += "### EXAMPLE 2 ####: \n" # EXAMPLE SETUP
      # prompt += "The Silesian War occured during which of the following answer choices?  " + '[' + '(A) ' + 'The War of Austrian Succession ' + ',' + '(B) ' + 'The War of Spanish Succession ' + ',' + '(C) ' + 'The Seven Years War ' + ',' + '(D) ' + 'The Spanish Inquisition ' + ']'
      # prompt += "Example output: (A)" # EXAMPLE ANSWER
      # prompt += "### END OF EXAMPLE 2###" # END OF EXAMPLE
      # prompt += 'Please answer the following question with either (A), (B), (C), or (D).' # PROMPT


    # elif task_name == "elementary_mathematics":
      # prompt = "You will need to solve an elementary math question. " # INSTRUCTION
      # prompt += "### Refer to the following example on how to answer a question:" # EXAMPLE SETUP
      # prompt += example_sample['input'] + '   ' + '[' + '(A) ' + example_sample['A'] + ',' + '(B) ' + example_sample['B'] + ',' + '(C) ' + example_sample['C'] + ',' + '(D) ' + example_sample['D'] + ']'
      # prompt += "Example output: (A)" # EXAMPLE ANSWER
      # prompt += "### END OF EXAMPLE ###" # END OF EXAMPLE
      # prompt += 'Please answer the following question with either (A), (B), (C), or (D).' # PROMPT

    modified_train_samples = []
    train_samples = train_samples[:-1]

    for i in range(len(train_samples['input'])):
        modified_sample = {key: train_samples[key][i] for key in train_samples}

        # modified_sample['input'] += '\n'
        # a_sample = modified_sample['A']
        # modified_sample['input'] += f'{{"A":"{a_sample}"}}'
        # b_sample = modified_sample['B']
        # modified_sample['input'] += f'{{"B":"{b_sample}"}}'
        # b_sample = modified_sample['C']
        # modified_sample['input'] += f'{{"C":"{b_sample}"}}'
        # b_sample = modified_sample['D']
        # modified_sample['input'] += f'{{"D":"{b_sample}"}}'
        # modified_sample['input'] += '\n'
        # modified_sample['input'] += "answer: {"
        modified_sample['input'] += '(A) ' + modified_sample['A']
        modified_sample['input'] += '(B)' + modified_sample['B']
        modified_sample['input'] += '(C)' + modified_sample['C']
        modified_sample['input'] += '(D)' + modified_sample['D']
        modified_sample['input'] += '"### Response: ('

        modified_train_samples.append(modified_sample)

    train_dataset = CustomDataset(modified_train_samples, tokenizer)
    dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False) ## Setting shuffle to False for consistency of outputs

    return dataloader

In [ ]:
'''
Initialize Dataloaders
'''


# task_name = "elementary_mathematics"
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-hf", token=os.environ.get('HF_TOKEN'), padding_side='left')
tokenizer.pad_token = tokenizer.unk_token
batch_size = 1

task_name = "astronomy"
eu_dataloader = create_dataloader(task_name, tokenizer, batch_size, False)

task_name = "elementary_mathematics"
em_dataloader = create_dataloader(task_name, tokenizer, batch_size, False)

tokenizer_config.json:   0%|          | 0.00/776 [00:00<?, ?B/s]

tokenizer.model:   0%|          | 0.00/500k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.84M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/414 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/datasets/load.py:1486: FutureWarning: The repository for lukaemon/mmlu contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/lukaemon/mmlu
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.war

Generating test split:   0%|          | 0/152 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/16 [00:00<?, ? examples/s]

Generating train split:   0%|          | 0/5 [00:00<?, ? examples/s]

/usr/local/lib/python3.10/dist-packages/datasets/load.py:1486: FutureWarning: The repository for lukaemon/mmlu contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/lukaemon/mmlu
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(


Generating test split:   0%|          | 0/378 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/41 [00:00<?, ? examples/s]

Generating train split:   0%|          | 0/5 [00:00<?, ? examples/s]

In [ ]:
import torch
from transformers import LlamaForCausalLM, LlamaConfig
from datasets import Dataset

# Create the Llama2 model configuration
dataloader_iter = iter(eu_dataloader)

for i in range(5):

  next_data = next(dataloader_iter)
  print(next_data)
  dataset_dict = {
      "input_ids" : [next_data],
      "labels" : [0],
  }


  dataset = Dataset.from_dict(dataset_dict)

  # print("Input text: ", input_text)
  # val =  tokenizer(input_text, padding='max_length', return_tensors="pt")['input_ids'] # try diff max len's
  # input_text = val

  # print(student_dataset["Input"].tolist())
  # dataset_dict = {
  #     "input_ids" : [input_text],
  #     "labels" : [target],
  # }

  # dataset = Dataset.from_dict(dataset_dict)

  if i == 0:
    curr_model = final_lora_model

  filename = f'finalized_teacher_logits/astronomy_{i}.npy'

  output_dir = f'results/checkpoint_{i}'
  curr_model = train(curr_model, tokenizer, dataset, output_dir, filename)
  print("MEMORY_ALLOCATED, ", torch.cuda.memory_allocated())

# # torch.save(curr_eu_model.state_dict(), 'model.pth')
# torch.cuda.empty_cache()
# gc.collect()

max_steps is given, it will override any value given in num_train_epochs


tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  What is true for a type-Ia ("type one-a") supernova?(A) This type occurs in binary systems.(B)This type occurs in young galaxies.(C)This type produces gamma-ray bursts.(D)This type produces high amounts of X-rays."### Response: (
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
finalized_teacher_logits/astronomy_0.npy
finalized_teacher_logits/astronomy_0.npy


`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.


Teacher:  torch.Size([100, 32000])


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Token:  50
Token:  100
Generated Text: What is true for a type-Ia ("type one-a") supernova?(A) This type occurs in binary systems.(B)This type occurs in young galaxies.(C)This type produces gamma-ray bursts.(D)This type produces high amounts of X-rays."### Response: (F)Atype-Iasupernovaisamassive,explosionofawhitedensestarthatoccursinbinarysystems.everybody-100-150solarmasses.theyareusuallybrightandproducealargeamountofenergyintherm...

Whatistrueforatype-Ia("typeone-a")supernova?

(A)Thistypeoccursinbinarysystems.
(
_______________________________________
torch.Size([100, 50])
Teacher:  torch.Size([100, 50])
Student:  torch.Size([100, 50])
loss tensor(0.4480, device='cuda:0', grad_fn=<NegBackward0>)


max_steps is given, it will override any value given in num_train_epochs


MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  If you know both the actual brightness of an object and its apparent brightness from your location then with no other information you can estimate:(A) Its speed relative to you(B)Its composition(C)Its size(D)Its distance from you"### Response: (
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
finalized_teacher_logits/astronomy_1.npy
finalized_teacher_logits/astronomy_1.npy
Teacher:  torch.Size([100, 32000])


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Token:  50
Token:  100
Generated Text: If you know both the actual brightness of an object and its apparent brightness from your location then with no other information you can estimate:(A) Its speed relative to you(B)Its composition(C)Its size(D)Its distance from you"### Response: (FT)Ifyouknowboththeactualbrightnessofanobjectanditsapparentbrightnessfromyourlocationthenwithnootherinformationyoucanestimateitsdistancefromyou.Unterscheidungbetween(A)and(D)isnotpossiblebasedonthisinformationalone.












































_______________________________________
torch.Size([100, 50])
Teacher:  torch.Size([100, 50])
Student:  torch.Size([100, 50])
loss tensor(0.5119, device='cuda:0', grad_fn=<NegBackward0>)


max_steps is given, it will override any value given in num_train_epochs


MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  Why is the sky blue?(A) Because the molecules that compose the Earth's atmosphere have a blue-ish color.(B)Because the sky reflects the color of the Earth's oceans.(C)Because the atmosphere preferentially scatters short wavelengths.(D)Because the Earth's atmosphere preferentially absorbs all other colors."### Response: (
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
finalized_teacher_logits/astronomy_2.npy
finalized_teacher_logits/astronomy_2.npy
Teacher:  torch.Size([100, 32000])


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Token:  50
Token:  100
Generated Text: Why is the sky blue?(A) Because the molecules that compose the Earth's atmosphere have a blue-ish color.(B)Because the sky reflects the color of the Earth's oceans.(C)Because the atmosphere preferentially scatters short wavelengths.(D)Because the Earth's atmosphere preferentially absorbs all other colors."### Response: (B)TheskyappearsbluebecauseitreflectsthecoloroftheEarth'soceans.nobodyknowsforsurewhytheskyappearsblue,butoneofthemostpopulartheoriesisthatit'sbecauseofreflection.Theoceansreflectlightbacktothesky,andtheblueshadowoftheseaontheskysurfaceappearsblue.ThisisknownasRayleighscattering,andit's
_______________________________________
torch.Size([100, 50])
Teacher:  torch.Size([100, 50])
Student:  torch.Size([100, 50])
loss tensor(0.4716, device='cuda:0', grad_fn=<NegBackward0>)


max_steps is given, it will override any value given in num_train_epochs


MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  You’ve made a scientific theory that there is an attractive force between all objects. When will your theory be proven to be correct?(A) The first time you drop a bowling ball and it falls to the ground proving your hypothesis.(B)After you’ve repeated your experiment many times.(C)You can never prove your theory to be correct only “yet to be proven wrong”.(D)When you and many others have tested the hypothesis."### Response: (
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
finalized_teacher_logits/astronomy_3.npy
finalized_teacher_logits/astronomy_3.npy
Teacher:  torch.Size([100, 32000])


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Token:  50
Token:  100
Generated Text: You’ve made a scientific theory that there is an attractive force between all objects. When will your theory be proven to be correct?(A) The first time you drop a bowling ball and it falls to the ground proving your hypothesis.(B)After you’ve repeated your experiment many times.(C)You can never prove your theory to be correct only “yet to be proven wrong”.(D)When you and many others have tested the hypothesis."### Response: (Mostlikelyanswer)Thecorrectansweris(D)Whenyouandmanypeoplehavetestedthehypothesis.Whileit'spossibletoformulateanattractiveforcebetweenobjectstheory,it'simportanttohaveevidenceandexperimentsupportingit.Unlessyouhavedoneexperimentsandobservedtheattractiveforceinaction,yourtheoryremainspurespeculation.Therefore,option(D)
_______________________________________
torch.Size([100, 50])
Teacher:  torch.Size([100, 50])
Student:  torch.Size([100, 50])
loss tensor(0.4060, device='cuda:0', grad_fn=<NegBackward0>)


max_steps is given, it will override any value given in num_train_epochs


MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  Which of the following is/are true?(A) Titan is the only outer solar system moon with a thick atmosphere(B)Titan is the only outer solar system moon with evidence for recent geologic activity(C)Titan's atmosphere is composed mostly of hydrocarbons(D)A and D"### Response: (
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
finalized_teacher_logits/astronomy_4.npy
finalized_teacher_logits/astronomy_4.npy
Teacher:  torch.Size([85, 32000])


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Token:  50
Generated Text: Which of the following is/are true?(A) Titan is the only outer solar system moon with a thick atmosphere(B)Titan is the only outer solar system moon with evidence for recent geologic activity(C)Titan's atmosphere is composed mostly of hydrocarbons(D)A and D"### Response: (Titanistheonlyoutersolarsystemmoonwithatickatmosphere)Titanisthonlyoutersolarsystemmoonwithatickatmosphere.everybodyknowsthis!Titan'satmosphereismadeupofmostlyhydrocarbons,andthereisnorecentgeologicactvityonthemoon.So,theonlyoptionthathasanytruthis(A
_______________________________________
torch.Size([85, 50])
Teacher:  torch.Size([85, 50])
Student:  torch.Size([85, 50])
loss tensor(0.6386, device='cuda:0', grad_fn=<NegBackward0>)


MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208


In [ ]:
from datasets import Dataset

dataloader_iter = iter(em_dataloader)

for i in range(10):

  next_data = next(dataloader_iter)
  print(next_data)
  dataset_dict = {
      "input_ids" : [next_data],
      "labels" : [0],
  }


  dataset = Dataset.from_dict(dataset_dict)

  # print("Input text: ", input_text)
  # val =  tokenizer(input_text, padding='max_length', return_tensors="pt")['input_ids'] # try diff max len's
  # input_text = val

  # print(student_dataset["Input"].tolist())
  # dataset_dict = {
  #     "input_ids" : [input_text],
  #     "labels" : [target],
  # }

  # dataset = Dataset.from_dict(dataset_dict)

  # if i == 0:
  #   curr_model = final_lora_model

  filename = f'finalized_teacher_logits/elementary_mathematics_{i}.npy'


  print(filename)


  output_dir = f'results/checkpoint_{i}'
  curr_model = train(curr_model, tokenizer, dataset, output_dir, filename)
  print("MEMORY_ALLOCATED, ", torch.cuda.memory_allocated())

# curr_model.save_pretrained('model.pth')
# torch.cuda.empty_cache()
# gc.collect()

max_steps is given, it will override any value given in num_train_epochs


tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
finalized_teacher_logits/elementary_mathematics_0.npy
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  What is the value of p in 24 = 2p?(A) p = 4(B)p = 8(C)p = 12(D)p = 24"### Response: (
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
finalized_teacher_logits/elementary_mathematics_0.npy
finalized_teacher_logits/elementary_mathematics_0.npy
Teacher:  torch.Size([100, 32000])


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Token:  50
Token:  100
Generated Text: What is the value of p in 24 = 2p?(A) p = 4(B)p = 8(C)p = 12(D)p = 24"### Response: (p=4)###Explanation:Theequation
_______________________________________
torch.Size([100, 50])
Teacher:  torch.Size([100, 50])
Student:  torch.Size([100, 50])
loss tensor(0.6338, device='cuda:0', grad_fn=<NegBackward0>)


max_steps is given, it will override any value given in num_train_epochs


MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
finalized_teacher_logits/elementary_mathematics_1.npy
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  Ms. Perez drove a total of 40 miles in 5 days. She drove the same number of miles each day. How many miles did Ms. Perez drive each day?(A) 5(B)7(C)8(D)9"### Response: (
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
finalized_teacher_logits/elementary_mathematics_1.npy
finalized_teacher_logits/elementary_mathematics_1.npy
Teacher:  torch.Size([7, 32000])


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Generated Text: Ms. Perez drove a total of 40 miles in 5 days. She drove the same number of miles each day. How many miles did Ms. Perez drive each day?(A) 5(B)7(C)8(D)9"### Response: (Ms.Perezdrove40
_______________________________________
torch.Size([7, 50])
Teacher:  torch.Size([7, 50])
Student:  torch.Size([7, 50])
loss tensor(0.9806, device='cuda:0', grad_fn=<NegBackward0>)


max_steps is given, it will override any value given in num_train_epochs


MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
finalized_teacher_logits/elementary_mathematics_2.npy
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  Find the quotient of −40 ÷ (−8).(A) 1 over 5(B)−5(C)−1 over 5(D)5"### Response: (
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
finalized_teacher_logits/elementary_mathematics_2.npy
finalized_teacher_logits/elementary_mathematics_2.npy
Teacher:  torch.Size([100, 32000])


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Token:  50
Token:  100
Generated Text: Find the quotient of −40 ÷ (−8).(A) 1 over 5(B)−5(C)−1 over 5(D)5"### Response: (1)
_______________________________________
torch.Size([100, 50])
Teacher:  torch.Size([100, 50])
Student:  torch.Size([100, 50])
loss tensor(0.8616, device='cuda:0', grad_fn=<NegBackward0>)


max_steps is given, it will override any value given in num_train_epochs


MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
finalized_teacher_logits/elementary_mathematics_3.npy
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  A soccer team has $90.00 to buy soccer balls. If one soccer ball costs $15.60, what is the greatest number of soccer balls the team can buy?(A) 4(B)5(C)6(D)7"### Response: (
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
finalized_teacher_logits/elementary_mathematics_3.npy
finalized_teacher_logits/elementary_mathematics_3.npy
Teacher:  torch.Size([100, 32000])


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Token:  50
Token:  100
Generated Text: A soccer team has $90.00 to buy soccer balls. If one soccer ball costs $15.60, what is the greatest number of soccer balls the team can buy?(A) 4(B)5(C)6(D)7"### Response: (B)
_______________________________________
torch.Size([100, 50])
Teacher:  torch.Size([100, 50])
Student:  torch.Size([100, 50])
loss tensor(0.8198, device='cuda:0', grad_fn=<NegBackward0>)


max_steps is given, it will override any value given in num_train_epochs


MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
finalized_teacher_logits/elementary_mathematics_4.npy
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  You and three friends go to a concert. The total cost for four tickets is $112. Write and solve an equation to find the cost of one ticket t.(A) 4t = 112; $448(B)4t = 112; $28(C)t over 4 = 112; $448(D)t over 4 = 112; $28"### Response: (
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
finalized_teacher_logits/elementary_mathematics_4.npy
finalized_teacher_logits/elementary_mathematics_4.npy
Teacher:  torch.Size([30, 32000])


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Generated Text: You and three friends go to a concert. The total cost for four tickets is $112. Write and solve an equation to find the cost of one ticket t.(A) 4t = 112; $448(B)4t = 112; $28(C)t over 4 = 112; $448(D)t over 4 = 112; $28"### Response: (1)
_______________________________________
torch.Size([30, 50])
Teacher:  torch.Size([30, 50])
Student:  torch.Size([30, 50])
loss tensor(1.2826, device='cuda:0', grad_fn=<NegBackward0>)


max_steps is given, it will override any value given in num_train_epochs


MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
finalized_teacher_logits/elementary_mathematics_5.npy
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  Use the expression below to answer the question. 3 × [(2 × 6 – 5) + (8 ÷ 4)] – 1 What is the value of the expression?(A) 9(B)11(C)26(D)32"### Response: (
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
finalized_teacher_logits/elementary_mathematics_5.npy
finalized_teacher_logits/elementary_mathematics_5.npy
Teacher:  torch.Size([100, 32000])


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Token:  50
Token:  100
Generated Text: Use the expression below to answer the question. 3 × [(2 × 6 – 5) + (8 ÷ 4)] – 1 What is the value of the expression?(A) 9(B)11(C)26(D)32"### Response: (1)
_______________________________________
torch.Size([100, 50])
Teacher:  torch.Size([100, 50])
Student:  torch.Size([100, 50])
loss tensor(0.6885, device='cuda:0', grad_fn=<NegBackward0>)


max_steps is given, it will override any value given in num_train_epochs


MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
finalized_teacher_logits/elementary_mathematics_6.npy
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  Write 1 and 1 over 11 as a whole or mixed number in simplest form.(A) 1.1 over 11(B)11 over 11(C)12 over 11(D)11 over 12"### Response: (
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
finalized_teacher_logits/elementary_mathematics_6.npy
finalized_teacher_logits/elementary_mathematics_6.npy
Teacher:  torch.Size([7, 32000])


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Generated Text: Write 1 and 1 over 11 as a whole or mixed number in simplest form.(A) 1.1 over 11(B)11 over 11(C)12 over 11(D)11 over 12"### Response: (1)
_______________________________________
torch.Size([7, 50])
Teacher:  torch.Size([7, 50])
Student:  torch.Size([7, 50])
loss tensor(1.5001, device='cuda:0', grad_fn=<NegBackward0>)


max_steps is given, it will override any value given in num_train_epochs


MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
finalized_teacher_logits/elementary_mathematics_7.npy
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  Find the quotient of 2.16 ÷ 0.06.(A) 3.6(B)36(C)0.01272(D)12.72"### Response: (
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
finalized_teacher_logits/elementary_mathematics_7.npy
finalized_teacher_logits/elementary_mathematics_7.npy
Teacher:  torch.Size([21, 32000])


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Generated Text: Find the quotient of 2.16 ÷ 0.06.(A) 3.6(B)36(C)0.01272(D)12.72"### Response: (1)
_______________________________________
torch.Size([21, 50])
Teacher:  torch.Size([21, 50])
Student:  torch.Size([21, 50])
loss tensor(0.8981, device='cuda:0', grad_fn=<NegBackward0>)


max_steps is given, it will override any value given in num_train_epochs


MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
finalized_teacher_logits/elementary_mathematics_8.npy
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  Find the difference of 142.76 – 16.5.(A) 159.26(B)2.224(C)14,111(D)126.26"### Response: (
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
finalized_teacher_logits/elementary_mathematics_8.npy
finalized_teacher_logits/elementary_mathematics_8.npy
Teacher:  torch.Size([11, 32000])


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Generated Text: Find the difference of 142.76 – 16.5.(A) 159.26(B)2.224(C)14,111(D)126.26"### Response: (142.76-16.5)
_______________________________________
torch.Size([11, 50])
Teacher:  torch.Size([11, 50])
Student:  torch.Size([11, 50])
loss tensor(1.3391, device='cuda:0', grad_fn=<NegBackward0>)


max_steps is given, it will override any value given in num_train_epochs


MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
finalized_teacher_logits/elementary_mathematics_9.npy
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  Find the quotient of 5.04/0.7(A) 0.72(B)0.702(C)10.0571(D)7.2"### Response: (
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
finalized_teacher_logits/elementary_mathematics_9.npy
finalized_teacher_logits/elementary_mathematics_9.npy
Teacher:  torch.Size([7, 32000])


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Generated Text: Find the quotient of 5.04/0.7(A) 0.72(B)0.702(C)10.0571(D)7.2"### Response: (100%correct)


_______________________________________
torch.Size([7, 50])
Teacher:  torch.Size([7, 50])
Student:  torch.Size([7, 50])
loss tensor(1.4893, device='cuda:0', grad_fn=<NegBackward0>)


MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208


In [ ]:
from datasets import Dataset

dataloader_iter = iter(eu_dataloader)
for j in range(5):
  temp = next(dataloader_iter)
# curr_em_model = AutoModelForCausalLM()
# curr_em_model.load_state_dict(torch.load('model.pth'))

for i in range(5, 10):

  next_data = next(dataloader_iter)
  print(next_data)
  dataset_dict = {
      "input_ids" : [next_data],
      "labels" : [0],
  }


  dataset = Dataset.from_dict(dataset_dict)

  # print("Input text: ", input_text)
  # val =  tokenizer(input_text, padding='max_length', return_tensors="pt")['input_ids'] # try diff max len's
  # input_text = val

  # print(student_dataset["Input"].tolist())
  # dataset_dict = {
  #     "input_ids" : [input_text],
  #     "labels" : [target],
  # }

  # dataset = Dataset.from_dict(dataset_dict)

  # if i == 0:
  #   curr_model = final_lora_model

  filename = f'finalized_teacher_logits/astronomy_{i}.npy'


  print(filename)


  output_dir = f'results/checkpoint_{i}'
  curr_model = train(curr_model, tokenizer, dataset, output_dir, filename)

  print("MEMORY_ALLOCATED, ", torch.cuda.memory_allocated())

max_steps is given, it will override any value given in num_train_epochs


tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
finalized_teacher_logits/astronomy_5.npy
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  A comet of mass m impacts the earth (mass M radius R) at the minimum impact speed. What is the expression for the total energy released in the impact?(A) m*v(B)0.5*m/(R^3)(C)0.5*m*(2GM/R)(D)0.6*G(M^2)/R"### Response: (
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
finalized_teacher_logits/astronomy_5.npy
finalized_teacher_logits/astronomy_5.npy
Teacher:  torch.Size([100, 32000])


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Token:  50
Token:  100
Generated Text: A comet of mass m impacts the earth (mass M radius R) at the minimum impact speed. What is the expression for the total energy released in the impact?(A) m*v(B)0.5*m/(R^3)(C)0.5*m*(2GM/R)(D)0.6*G(M^2)/R"### Response: (Massofcomet=m,massofearth=M,radiusofearth=R,radiusofcomet=a,gravitationalconstant=G)

Thetotalenergyreleasedinanimpactbetweenacometandtheearthcanbeestimatedusingthefollowingexpression:

$$E=\frac{1}{2}\frac{m}{M}\left(\frac{v^2}{R}\right)$$

wherev
_______________________________________
torch.Size([100, 50])
Teacher:  torch.Size([100, 50])
Student:  torch.Size([100, 50])
loss tensor(0.9862, device='cuda:0', grad_fn=<NegBackward0>)


max_steps is given, it will override any value given in num_train_epochs


MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
finalized_teacher_logits/astronomy_6.npy
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  Some of Mars'water is frozen in the soil and the ice caps and some was lost due to solar wind stripping but much of the original water is thought to have been lost through another mechanism. What happened to this "lost"water?(A) it was stripped away by the magnetic field when it rapidly decreased in strength(B)it was broken into hydrogen and oxygen by ultraviolet light and the hydrogen was lost through thermal escape(C)it was consumed by a civilization of thirsty Martians(D)it was vaporized during a period of intense volcanism and was lost to space through thermal escape"### Response: (
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
finalized_teacher_logits/

/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Token:  50
Token:  100
Generated Text: Some of Mars'water is frozen in the soil and the ice caps and some was lost due to solar wind stripping but much of the original water is thought to have been lost through another mechanism. What happened to this "lost"water?(A) it was stripped away by the magnetic field when it rapidly decreased in strength(B)it was broken into hydrogen and oxygen by ultraviolet light and the hydrogen was lost through thermal escape(C)it was consumed by a civilization of thirsty Martians(D)it was vaporized during a period of intense volcanism and was lost to space through thermal escape"### Response: (Mars'waterwaslostthroughthermalescape)

Theansweris(D)itwasvaporizedduringapermofintensevolcanismandwastlosttospacethroughthermalescape.Mars'waterwaslostthroughthermalescape.

Explanation:

Themostlikelyexplanationforthe"lost"wateronMarsisthatitwasvaporizedduringapermofintensevolcanism.Thisisbased
_______________________________________
torch.Size([100, 50

max_steps is given, it will override any value given in num_train_epochs


MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
finalized_teacher_logits/astronomy_7.npy
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  Most rocks on the Moon's surface are older than those on the Earth's surface. The best evidence for this is:(A) Lunar rocks are composed of fragments pulverized by many impacts.(B)Radioactive dating of lunar samples shows that they are older.(C)The Moon's surface is more heavily eroded than the Earth's surface.(D)The Moon's surface has more impact craters than the Earth's surface."### Response: (
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
finalized_teacher_logits/astronomy_7.npy
finalized_teacher_logits/astronomy_7.npy
Teacher:  torch.Size([27, 32000])


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Generated Text: Most rocks on the Moon's surface are older than those on the Earth's surface. The best evidence for this is:(A) Lunar rocks are composed of fragments pulverized by many impacts.(B)Radioactive dating of lunar samples shows that they are older.(C)The Moon's surface is more heavily eroded than the Earth's surface.(D)The Moon's surface has more impact craters than the Earth's surface."### Response: (Mostlikelyanswer)Thebestevidenceforthisis(B)Radioactivedatingoflunarsamplesshowstheyareolder
_______________________________________
torch.Size([27, 50])
Teacher:  torch.Size([27, 50])
Student:  torch.Size([27, 50])
loss tensor(0.5214, device='cuda:0', grad_fn=<NegBackward0>)


max_steps is given, it will override any value given in num_train_epochs


MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
finalized_teacher_logits/astronomy_8.npy
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  What is the second most common element in the solar system?(A) Iron(B)Hydrogen(C)Methane(D)Helium"### Response: (
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
finalized_teacher_logits/astronomy_8.npy
finalized_teacher_logits/astronomy_8.npy
Teacher:  torch.Size([100, 32000])


/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Token:  50
Token:  100
Generated Text: What is the second most common element in the solar system?(A) Iron(B)Hydrogen(C)Methane(D)Helium"### Response: (M)Helium.Unterscheidung:Heliumisthesecondmostcommonelementinthesolarsystem,makingupapproximately28%ofthenuclearsun'smassand300timesmorethanallotherelementscombined.Theotheranswersareincorrect.Ironisnotcommoninthenuclearsun,hydrogenisnotfoundinthenuclearsun,andmethaneisnotfoundinthenuclearsun.
_______________________________________
torch.Size([100, 50])
Teacher:  torch.Size([100, 50])
Student:  torch.Size([100, 50])
loss tensor(0.5484, device='cuda:0', grad_fn=<NegBackward0>)


max_steps is given, it will override any value given in num_train_epochs


MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])
finalized_teacher_logits/astronomy_9.npy
.....Computing Loss , Generating Outputs.........
Val:  tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
Input Text:  What is the source of the material that causes meteor showers?(A) Near-Earth asteroids gradually disintegrate and spread out along their orbital path. When the Earth passes through the orbit of an asteroid we are bombarded by sand-sized particles which cause a meteor shower.(B)Near-Earth asteroids disintegrate as they enter Earth's atmosphere creating hundreds of bright meteors that appear to radiate from a single location in the sky.(C)The nuclei of comets disintigrate as they enter Earth's atmosphere creating hundreds of bright meteors that appear to radiate from a central location in the sky.(D)The nuclei of comets gradually disintegrate and spread out along the comet's orbital path.

/usr/local/lib/python3.10/dist-packages/torch/utils/checkpoint.py:460: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(


Token:  0
Token:  50
Token:  100
Generated Text: What is the source of the material that causes meteor showers?(A) Near-Earth asteroids gradually disintegrate and spread out along their orbital path. When the Earth passes through the orbit of an asteroid we are bombarded by sand-sized particles which cause a meteor shower.(B)Near-Earth asteroids disintegrate as they enter Earth's atmosphere creating hundreds of bright meteors that appear to radiate from a single location in the sky.(C)The nuclei of comets disintigrate as they enter Earth's atmosphere creating hundreds of bright meteors that appear to radiate from a central location in the sky.(D)The nuclei of comets gradually disintegrate and spread out along the comet's orbital path. When the Earth passes through the orbit of a comet we are bombarded by sand-sized particles which cause a meteor shower."### Response: (Meteorshowersarecausedbythedisintegrationofasteroidsandcomets.Thematerialthatcausesmeteorshowerscomesfromtheasteroidsan

MEMORY ALLOCATED:  4538179584
MEMORY_ALLOCATED,  4529502208


# Custom Trainer Class (Not Using)

In [ ]:
# @title
class CustomTrainer(Trainer):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.count = 0
    def compute_loss(self, model, inputs):
        """
        Overrides the compute_loss method to use a custom KL divergence loss.

        Args:
            model (PreTrainedModel): The model to train.
            inputs (Dict[str, torch.Tensor]): The input data.

        Returns:
            torch.Tensor: The custom loss value.
        """
        print(".....Computing Loss , Generating Outputs.........")
        softmax = nn.Softmax(dim=-1)
        print('inputs', inputs)

        model_in = inputs['input_ids'].squeeze(0)
        print(model_in)
        outputs = model.generate(model_in, max_new_tokens=5, output_logits=True, return_dict_in_generate=True, num_return_sequences=1, encoder_no_repeat_ngram_size=2) #, return_logits=True
        logits = outputs[0]
        print('logits shape', logits.shape)
        student_logits = softmax(logits.float())
        student_top_k_probs, _ = torch.topk(student_logits, 50, dim=-1)
        student_normalized_probs = student_top_k_probs / torch.sum(student_top_k_probs, dim=-1, keepdim=True)

        kl_div = nn.KLDivLoss(reduction='batchmean')
        loss = kl_div(student_normalized_probs, teacher_normalized_probs)

        self.count += 1
        return loss

In [ ]:
# @title
import torch
from transformers import Trainer, TrainingArguments
import torch.nn.functional as F
from transformers import LogitsProcessorList, MinLengthLogitsProcessor, StoppingCriteriaList, MaxLengthCriteria
import numpy as np
from trl import SFTTrainer
import torch.nn as nn


count = 0

filename = f'teacher_logits/test_logits_2.npy'
teacher_logits = np.load(filename)
teacher_logits = torch.from_numpy(teacher_logits)
teacher_top_k_probs, teacher_top_k_indices = torch.topk(teacher_logits, 50, dim=-1)
teacher_normalized_probs = teacher_top_k_probs / torch.sum(teacher_top_k_probs, dim=-1, keepdim=True)
teacher_normalized_probs = teacher_normalized_probs.to('cuda')

# freeing memory beforehand
torch.cuda.empty_cache()
gc.collect()


# # Define custom KL divergence loss function
# def kl_divergence_loss(output_logits, target_logits):
#     output_logits = output_logits.to('cuda')
#     target_logits = target_logits.to('cuda')
#     return F.kl_div(output_logits, target_logits, reduction='batchmean')


# Modify training loop to use KL divergence loss
def train(model, tokenizer, dataset, output_dir):
    # Training parameters
    training_args = TrainingArguments(
        per_device_train_batch_size=1,
        per_device_eval_batch_size=1,
        gradient_accumulation_steps=1,
        # warmup_steps=2,
        max_steps=1,
        num_train_epochs=1,
        output_dir=output_dir,
        evaluation_strategy="epoch",
        logging_strategy="epoch",
        save_strategy="epoch",
        gradient_checkpointing=True,
        fp16=True,
        load_best_model_at_end=True,
        optim="paged_adamw_8bit", # "ingredient 3", paged optimizers
    )

    trainer = CustomTrainer(
        model=model,
        args=training_args,
        train_dataset=dataset,
    )

    trainer.train()

# Assuming the model and dataset are already defined
print('......Set tokenizer.......')
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-chat-hf", token=os.environ.get('HF_TOKEN'))
tokenizer.pad_token = tokenizer.unk_token


output_dir = "results/final_checkpoint"
train(model, tokenizer, dataset, output_dir)

# Attempt with BERT like trainer

In [ ]:
# @title
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from tqdm import tqdm

class LlamaTrainer:
    """ A training and evaluation loop for PyTorch models with a BERT like architecture. """


    def __init__(
        self,
        teacher_model,
        student_model,
        tokenizer,
        train_dataloader,
        eval_dataloader=None,
        epochs=1,
        lr=5e-04,
        output_dir='./',
        output_filename='model_state_dict.pt',
        save=False,
        tabular=False,
    ):
        """
        Args:
            model: torch.nn.Module: = A PyTorch model with a BERT like architecture,
            tokenizer: = A BERT tokenizer for tokenizing text input,
            train_dataloader: torch.utils.data.DataLoader =
                A dataloader containing the training data with "text" and "label" keys (optionally a "tabular" key),
            eval_dataloader: torch.utils.data.DataLoader =
                A dataloader containing the evaluation data with "text" and "label" keys (optionally a "tabular" key),
            epochs: int = An integer representing the number epochs to train,
            lr: float = A float representing the learning rate for the optimizer,
            output_dir: str = A string representing the directory path to save the model,
            output_filename: string = A string representing the name of the file to save in the output directory,
            save: bool = A boolean representing whether or not to save the model,
            tabular: bool = A boolean representing whether or not the BERT model is modified to accept tabular data,
        """

        self.device = 'cuda' if torch.cuda.is_available() else 'cpu'
        self.model = model.to(self.device)
        self.tokenizer = tokenizer
        self.train_dataloader = train_dataloader
        self.eval_dataloader = eval_dataloader
        self.optimizer = torch.optim.AdamW(self.model.parameters(), lr=lr)
        self.loss_fn = nn.CrossEntropyLoss() ##### Modify this to KL divergence
        self.output_dir = output_dir
        self.output_filename = output_filename
        self.save = save
        self.eval_loss = float('inf')  # tracks the lowest loss so as to only save the best model
        self.epochs = epochs
        self.epoch_best_model = 0  # tracks which epoch the lowest loss is in so as to only save the best model
        self.tabular = tabular
        self.teacher_model = teacher_model
        self.student_model = student_model

    def train(self, evaluate=False):
        """ Calls the batch iterator to train and optionally evaluate the model."""
        for epoch in range(self.epochs):
            self.iteration(epoch, self.train_dataloader)
            if evaluate and self.eval_dataloader is not None:
                self.iteration(epoch, self.eval_dataloader, train=False)

    def evaluate(self):
        """ Calls the batch iterator to evaluate the model."""
        epoch=0
        self.iteration(epoch, self.eval_dataloader, train=False)

    def iteration(self, epoch, data_loader, train=True):
        """ Iterates through one epoch of training or evaluation"""

        # initialize variables
        loss_accumulated = 0.
        correct_accumulated = 0
        samples_accumulated = 0
        preds_all = []
        labels_all = []

        self.model.train() if train else self.model.eval()

        # progress bar
        mode = "train" if train else "eval"
        batch_iter = tqdm.tqdm(
            enumerate(data_loader),
            desc=f"EP ({mode}) {epoch}",
            total=len(data_loader),
            bar_format="{l_bar}{r_bar}"
        )

        # iterate through batches of the dataset
        for i, batch in batch_iter:

            # tokenize data
            batch_t = self.tokenizer(
                batch['text'],
                padding='max_length',
                max_length=512,
                truncation=True,
                return_tensors='pt',
            )
            batch_t = {key: value.to(self.device) for key, value in batch_t.items()}
            batch_t["input_labels"] = batch["label"].to(self.device)
            batch_t["tabular_vectors"] = batch["tabular"].to(self.device)

            # forward pass - include tabular data if it is a tabular model
            if self.tabular:
                logits = self.model(
                    input_ids=batch_t["input_ids"],
                    token_type_ids=batch_t["token_type_ids"],
                    attention_mask=batch_t["attention_mask"],
                    tabular_vectors=batch_t["tabular_vectors"],
                )

            else:
                student_logits = self.student_model(
                    input_ids=batch_t["input_ids"],
                    token_type_ids=batch_t["token_type_ids"],
                    attention_mask=batch_t["attention_mask"],
                )
                teacher_logits = self.teacher_model()

            # calculate loss
            loss = self.loss_fn(student_logits, teacher_logits, batch_t["input labels"])
            # loss = self.loss_fn(logits, batch_t["input_labels"])

            # compute gradient and and update weights
            if train:
                self.optimizer.zero_grad()
                loss.backward()
                self.optimizer.step()

            # calculate the number of correct predictions
            preds = logits.argmax(dim=-1)
            correct = preds.eq(batch_t["input_labels"]).sum().item()

            # accumulate batch metrics and outputs
            loss_accumulated += loss.item()
            correct_accumulated += correct
            samples_accumulated += len(batch_t["input_labels"])
            preds_all.append(preds.detach())
            labels_all.append(batch_t['input_labels'].detach())

        # concatenate all batch tensors into one tensor and move to cpu for compatibility with sklearn metrics
        preds_all = torch.cat(preds_all, dim=0).cpu()
        labels_all = torch.cat(labels_all, dim=0).cpu()

        # metrics
        accuracy = accuracy_score(labels_all, preds_all)
        precision = precision_score(labels_all, preds_all, average='macro')
        recall = recall_score(labels_all, preds_all, average='macro')
        f1 = f1_score(labels_all, preds_all, average='macro')
        avg_loss_epoch = loss_accumulated / len(data_loader)

        # print metrics to console
        print(
            f"samples={samples_accumulated}, \
            correct={correct_accumulated}, \
            acc={round(accuracy, 4)}, \
            recall={round(recall, 4)}, \
            prec={round(precision,4)}, \
            f1={round(f1, 4)}, \
            loss={round(avg_loss_epoch, 4)}"
        )

        # save the model if the evaluation loss is lower than the previous best epoch
        if self.save and not train and avg_loss_epoch < self.eval_loss:

            # create directory and filepaths
            dir_path = Path(self.output_dir)
            dir_path.mkdir(parents=True, exist_ok=True)
            file_path = dir_path / f"{self.output_filename}_epoch_{epoch}.pt"

            # delete previous best model from hard drive
            if epoch > 0:
                file_path_best_model = dir_path / f"{self.output_filename}_epoch_{self.epoch_best_model}.pt"
                !rm -f $file_path_best_model

            # save model
            torch.save({
                'model_state_dict': self.model.state_dict(),
                'optimizer_state_dict': self.optimizer.state_dict()
            }, file_path)

            # update the new best loss and epoch
            self.eval_loss = avg_loss_epoch
            self.epoch_best_model = epoch

In [ ]:
# @title
# Qlora,

from peft import prepare_model_for_kbit_training, LoraModel, LoraConfig, get_peft_model
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

config = LoraConfig(
    task_type="SEQ_2_SEQ_LM",
    r=8,
    lora_alpha=32,
    target_modules=["q_proj", "v_proj"],
    lora_dropout=0.01,
)

model = prepare_model_for_kbit_training(model)
lora_model = LoraModel(model, config, "default")

In [ ]:
# @title
n_params = 0
n_trainable_params = 0

# count the number of trainable parameters
for n, p in lora_model.named_parameters():
    n_params += p.numel()
    if p.requires_grad:
        n_trainable_params += p.numel()

print(f"Total parameters: {n_params}")
print(f"Trainable parameters: {n_trainable_params}")
print(f"Percentage trainable: {round(n_trainable_params / n_params * 100, 2)}%")

In [ ]:
# @title
from datasets import load_dataset
import pandas as pd

class CustomDataset(Dataset):
    def __init__(self, currDataset, max_length=45, isTeacher=False):
        self.currDataset = currDataset
        # self.tokenizer = tokenizer
        self.max_length = max_length
        self.label_translation = {"A": 1, "B" : 2, "C": 3, "D": 4}
        self.isTeacher = isTeacher

    def __len__(self):
        return len(self.currDataset)

    def __getitem__(self, idx):
        input = self.currDataset.iloc[idx]['input']
        answer_a = self.currDataset.iloc[idx]['A']
        answer_b = self.currDataset.iloc[idx]['B']
        answer_c = self.currDataset.iloc[idx]['C']
        answer_d = self.currDataset.iloc[idx]['D']
        labels = self.currDataset.iloc[idx]['target']
        # data = self.currDataset[idx]
        # input_text = data['input']
        # inputs = self.tokenizer(input_text, padding='max_length', truncation=True, max_length=self.max_length, return_tensors="pt")
        # # labels = torch.tensor(data['target'], dtype=torch.long)
        # print(inputs)
        # labels = torch.tensor(self.label_translation[data['target']], dtype=torch.long)
        # print(labels)
        return input, answer_a, answer_b, answer_c, answer_d, labels

def create_dataloader(task_name, tokenizer, batch_size=16, isTeacher=False):
    dataset = load_dataset("lukaemon/mmlu", task_name)
    train_samples = dataset['test']

    example_sample = dataset['test'][-1]
    prompt = "You will need to solve a math question. Example Input: "
    prompt += example_sample['input']
    prompt += " A: "
    prompt += example_sample['A']
    prompt += " B: "
    prompt += example_sample['B']
    prompt += " C: "
    prompt += example_sample['C']
    prompt += " D: "
    prompt += example_sample['D']
    prompt += " Example Output "
    prompt += example_sample['target']
    prompt += " Now complete the following math question."

    train_dataset = CustomDataset(dataset['test'], tokenizer)
    train_samples = train_samples[:-1]
    for sample in train_samples['input']:
      sample = prompt + '\n' + sample
      print(sample)

    dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

    if isTeacher:
      pass
    else:
      pass

    return dataloader

In [ ]:
# @title
train_df = pd.read_csv('./elementary_mathematics.csv', header=0)
val_df =  pd.read_csv('./elementary_mathematicsValidation.csv', header=0)

In [ ]:
# @title
print(train_df.columns)

In [ ]:
# @title
train_dataset = CustomDataset(train_df, max_length=100, isTeacher=True)

In [ ]:
# @title
val_dataset = CustomDataset(val_df, max_length=100, isTeacher=True)

In [ ]:
# @title
BATCH_SIZE = 4

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE)
val_loader  = DataLoader(val_dataset, batch_size=BATCH_SIZE)

In [ ]:
# @title
import torch
import torch.nn as nn
import torch.nn.functional as F
import tqdm

In [ ]:
# @title
mode = "train" if True else "eval"
batch_iter = tqdm.tqdm(
    enumerate(train_loader),
    desc=f"EP ({mode}) {1}",
    total=len(train_loader),
    bar_format="{l_bar}{r_bar}"
)
for b in batch_iter:
  print(b)
# for i, batch in batch_iter:
#   print("Test")
#   break

In [ ]:
# @title
#bert base lora all r = 8
trainer_llama_base_lora = LlamaTrainer(
    model,
    None,
    tokenizer_base,
    lr=5e-04,
    epochs=10,
    train_dataloader=train_loader,
    eval_dataloader=val_loader,
    output_dir='../models/llama2_benchmark',
    output_filename='llama2_lora_teacher',
    save=True,
)

trainer_llama_base_lora.train(evaluate=True)