<a href="https://colab.research.google.com/github/Karthik-Kundurthy/context_distillation/blob/main/Teacher_model_context_distillation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Setup

- Mounting Drive
- hugging face auth
- pip installs

In [ ]:
# @title
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
# @title
import os
from getpass import getpass

# os.environ['HF_TOKEN'] = getpass('Enter your Hugging Face API token: ')
os.environ['HF_TOKEN'] = "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"

In [ ]:
# @title
!pip install datasets
!pip install transformers
!pip install bitsandbytes
!pip install accelerate
!pip install torch

# European History Custom Dataset

- Custom Dataset Class
- Prompt Engineering
- initializing and getting formats of european_history and elementary_math dataloaders

In [ ]:
# @title
# # @title
#   '''
#   Examples
#   '''
#   # prompt += "### Instruction= Example question 1: "
#   # prompt += "What was the ruling house of Prussia?"
#   # prompt += "(A) Bourbons "
#   # # prompt += "\n"
#   # prompt += "(B) Habsburgs "
#   # # prompt += "\n"
#   # prompt += "(C) Hohenzollerns "
#   # # prompt += "\n"
#   # prompt += "(D) Romanovs "
#   # # prompt += "\n"
#   # prompt += "Example Output: (C)"
#   # prompt += "\n##### End of Example 1 ########\n"
#   # prompt += "### Example question 2: "
#   # prompt += "The Silesian War occured during which of the following answer choices?"
#   # prompt += "(A) The War of Austrian Succession "
#   # # prompt += "\n"
#   # prompt += "(B) The War of Spanish Succession "
#   # # prompt += "\n"
#   # prompt += "(C) The Seven Years War "
#   # # prompt += "\n"
#   # prompt += "(D) The Spanish Inquisition "
#   # # prompt += "\n"
#   # prompt += "Example Output: (A)"
#   # prompt += "\n##### End of Example 2 ########"
#   # prompt += "### End of Instruction ###"
#   # prompt += "### Response: ("

#   # prompt += "### Instruction: Example question 1"
#   # prompt += example_sample['input']
#   # prompt += "(A) "
#   # prompt += example_sample['A'] + " "
#   # prompt += "(B) "
#   # prompt += example_sample['B'] + " "
#   # prompt += "(C) "
#   # prompt += example_sample['C'] + " "
#   # prompt += "(D) "
#   # prompt += example_sample['D']  + " "
#   # prompt += "\nExample Output: A"
#   # prompt += "\nScratchpad: We need to understand the relationship between the total number of people and the number of people each boat can hold. The problem states that there are 25 people and each boat holds 5 people. To find out how many boats are needed, we should divide the total number of people by the number of people each boat can accommodate. Therefore, by dividing 25 by 5, we get 5, which represents the number of boats needed. This matches option B: Divide 25 by 5, making it the correct answer as it directly addresses how to calculate the number of groups (boats) when given a total (people) and the size of each group (boat capacity)."
#   # prompt += f"<option> {example_sample['target']}"
#   # prompt += "\n##### End of Example ########"
#   # prompt += " Now complete the following math question. Answer the question with either (A), (B), (C), or (D). DO NOT repeat any part of the example in the answer."
#   # prompt += "### Response: ("

In [ ]:
import torch
from torch.utils.data import DataLoader, Dataset
from transformers import AutoTokenizer, AutoModelForCausalLM
from datasets import load_dataset

class CustomDataset(Dataset):
    def __init__(self, currDataset, tokenizer, max_length=2048, isTeacher=False):
        self.currDataset = currDataset
        self.tokenizer = tokenizer
        self.max_length = max_length
        self.label_translation = {"A": 1, "B" : 2, "C": 3, "D": 4}
        self.isTeacher = isTeacher

    def __len__(self):
        return len(self.currDataset)

    def __getitem__(self, idx):
        data = self.currDataset[idx]
        input_text = data['input'][:self.max_length]
        inputs = self.tokenizer(input_text, padding='max_length', truncation=True, max_length=self.max_length, return_tensors="pt")
        return inputs.input_ids.squeeze(0)

def create_dataloader(task_name, tokenizer, batch_size=16, isTeacher=False):
    dataset = load_dataset("lukaemon/mmlu", task_name)
    train_samples = dataset['test']

    example_sample = dataset['test'][-1] # get a standard test example to use


    # prompt = "You will need to solve a high school math question. Answer the question with ONLY (A), (B), (C), or (D) please."

    prompt = ""
    if task_name == "high_school_european_history":
      prompt = "You will need to solve a high school European history question." # INSTRUCTION
      prompt += "### EXAMPLE 1 ####: \n" # EXAMPLE SETUP
      prompt += "What was the ruling house of Prussia?  " + '[' + '(A) ' + 'Bourbons ' + ',' + '(B) ' + 'Habsburgs ' + ',' + '(C) ' + 'Hohenzollerns' + ',' + '(D) ' + 'Romanovs ' + ']'
      prompt += "Example output: (C)" # EXAMPLE ANSWER
      prompt += "### END OF EXAMPLE 1###" # END OF EXAMPLE
      prompt += "### EXAMPLE 2 ####: \n" # EXAMPLE SETUP
      prompt += "The Silesian War occured during which of the following answer choices?  " + '[' + '(A) ' + 'The War of Austrian Succession ' + ',' + '(B) ' + 'The War of Spanish Succession ' + ',' + '(C) ' + 'The Seven Years War ' + ',' + '(D) ' + 'The Spanish Inquisition ' + ']'
      prompt += "Example output: (A)" # EXAMPLE ANSWER
      prompt += "### END OF EXAMPLE 2###" # END OF EXAMPLE
      prompt += 'Please answer the following question with either (A), (B), (C), or (D).' # PROMPT

    if task_name == "astronmy":
      example_sample = dataset['test'][-3]
      prompt = "You will need to solve an astronomy question." # INSTRUCTION
      prompt += "### EXAMPLE 1 ####: \n" # EXAMPLE SETUP
      prompt += example_sample['input'] + '   ' + '[' + '(A) ' + example_sample['A'] + ',' + '(B) ' + example_sample['B'] + ',' + '(C) ' + example_sample['C'] + ',' + '(D) ' + example_sample['D'] + ']'
      prompt += "Example output: (A)" # EXAMPLE ANSWER
      prompt += "### END OF EXAMPLE ###" # END OF EXAMPLE
      prompt += 'Please answer the following question with either (A), (B), (C), or (D).' # PROMPT


    elif task_name == "elementary_mathematics":
      prompt = "You will need to solve an elementary math question. " # INSTRUCTION
      prompt += "### Refer to the following example on how to answer a question:" # EXAMPLE SETUP
      prompt += example_sample['input'] + '   ' + '[' + '(A) ' + example_sample['A'] + ',' + '(B) ' + example_sample['B'] + ',' + '(C) ' + example_sample['C'] + ',' + '(D) ' + example_sample['D'] + ']'
      prompt += "Example output: (A)" # EXAMPLE ANSWER
      prompt += "### END OF EXAMPLE ###" # END OF EXAMPLE
      prompt += 'Please answer the following question with either (A), (B), (C), or (D).' # PROMPT

    modified_train_samples = []
    train_samples = train_samples[:-1]

    for i in range(len(train_samples['input'])):
        modified_sample = {key: train_samples[key][i] for key in train_samples}
        modified_sample['input'] = prompt + '\n' + modified_sample['input']
        modified_sample['input'] += '(A) ' + modified_sample['A']
        modified_sample['input'] += '(B)' + modified_sample['B']
        modified_sample['input'] += '(C)' + modified_sample['C']
        modified_sample['input'] += '(D)' + modified_sample['D']
        modified_sample['input'] += '"### Response: ('
        modified_train_samples.append(modified_sample)

    train_dataset = CustomDataset(modified_train_samples, tokenizer)
    dataloader = DataLoader(train_dataset, batch_size=batch_size, shuffle=False) ## Setting shuffle to False for consistency of outputs

    return dataloader





In [ ]:
'''
Initialize Dataloaders
'''


# task_name = "elementary_mathematics"
tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-hf", token=os.environ.get('HF_TOKEN'), padding_side='left')
tokenizer.pad_token = tokenizer.unk_token
batch_size = 1

# task_name = "high_school_european_history"
# eu_dataloader = create_dataloader(task_name, tokenizer, batch_size, False)

task_name = "astronomy"
a_dataloader = create_dataloader(task_name, tokenizer, batch_size, False)

# task_name = "elementary_mathematics"
# em_dataloader = create_dataloader(task_name, tokenizer, batch_size, False)



# tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-hf", token=os.environ.get('HF_TOKEN'), padding_side='left')
# tokenizer.pad_token = tokenizer.unk_token

# batch_size = 1


/usr/local/lib/python3.10/dist-packages/datasets/load.py:1486: FutureWarning: The repository for lukaemon/mmlu contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/lukaemon/mmlu
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(


In [ ]:
'''
Print european_history format
'''
for i, inputs in enumerate(eu_dataloader):
    print(f"Processing batch {i+1}")
    print(inputs)
    break

Processing batch 1
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])


In [ ]:
'''
Print elementary_mathematics format
'''
for i, inputs in enumerate(em_dataloader):
    print(f"Processing batch {i+1}")
    print(inputs)
    break

Processing batch 1
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]])


# Initialize Teacher Model

In [ ]:
'''
# Generate Distribution of Teacher Model
# Quantized Llama - https://medium.com/@lucnguyen_61589/llama-2-using-huggingface-part-1-3a29fdbaa9ed

'''
from transformers import AutoTokenizer, AutoModelForCausalLM
from torch import cuda, bfloat16
from transformers import BitsAndBytesConfig

### Step 1 : Import and create bit and bytes config ###
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.bfloat16,
    llm_int8_enable_fp32_cpu_offload=True
)

### Step 2 : Loading model with quantization config ###
model = AutoModelForCausalLM.from_pretrained("meta-llama/Llama-2-7b-chat-hf", device_map={"": 0}, quantization_config=bnb_config, token=os.environ.get('HF_TOKEN'))
if torch.cuda.is_available():
    print("GPU detected. Using GPU for inference.")
    # model = model.to("cuda")

model.eval()


config.json:   0%|          | 0.00/614 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/9.98G [00:00<?, ?B/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.50G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/188 [00:00<?, ?B/s]

GPU detected. Using GPU for inference.


LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(32000, 4096)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaSdpaAttention(
          (q_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear4bit(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear4bit(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear4bit(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLU()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
    )
    (norm): Lla

In [ ]:
%cd drive/MyDrive/"CS 7643 - Project"

/content/drive/.shortcut-targets-by-id/1Lb1kmegrlLW6PSJzuwWZ1N1kYDI5y7U3/CS 7643 - Project


#Generate Teacher Logits

In [ ]:
import numpy as np
import torch
import torch.nn.functional as F
import gc

results = []
prompts = []

# dataloaders = [eu_dataloader, em_dataloader]
dataloaders = [a_dataloader]

# freeing memory beforehand
torch.cuda.empty_cache()
gc.collect()
outputs = None
for idx, dataloader in enumerate(dataloaders):
  for i, inputs in enumerate(dataloader):
    if i == 20:  # Add a break to check outputs
      break

    if idx == 0:
      task_name = "astronomy"
      # task_name = "high_school_european_history"
    else:
      task_name = "elementary_mathematics"

    ### Print Statements
    print('TASK: ', task_name, '...')
    print('ITERATION: ', i, '...')
    print(f"PROCESSING BATCH {i+1} of {task_name} ... ")
    prompts.append(inputs)
    inputs = inputs.to('cuda')

    ### Get the output and Generated Text ###
    print(inputs)
    # inputs = tokenizer(inputs, return_tensors="pt").to('cuda')
    outputs = model.generate(inputs, max_new_tokens=100, output_logits=True, output_scores=True, return_dict_in_generate=True, num_return_sequences=1, encoder_no_repeat_ngram_size=2) #, return_logits=True
    print(outputs.keys())

    print('GENERATED TEXT', tokenizer.decode(outputs.sequences[0], skip_special_tokens=True))


    logits = torch.stack(outputs.logits)
    print(logits.shape)



    #### Save to Numpy array ####
    file_name = f'finalized_teacher_logits/{task_name}_{i}.npy'
    numpy_array = logits.cpu().numpy()
    np.save(file_name, numpy_array)

    print("MEMORY ALLOCATED: ", torch.cuda.memory_allocated())

    print("_____________________________________________________________________________________________________________________")







TASK:  astronomy ...
ITERATION:  0 ...
PROCESSING BATCH 1 of astronomy ... 
tensor([[    0,     0,     0,  ..., 13291, 29901,   313]], device='cuda:0')
odict_keys(['sequences', 'scores', 'logits', 'past_key_values'])
GENERATED TEXT 
What is true for a type-Ia ("type one-a") supernova?(A) This type occurs in binary systems.(B)This type occurs in young galaxies.(C)This type produces gamma-ray bursts.(D)This type produces high amounts of X-rays."### Response: (A). Type Ia supernovae (SNe Ia) occur in close binary star systems, typically consisting of a white dwarf (WD) and a companion star. The WD accumulates material from the companion star through gravitational forces until it reaches a critical mass, causing a thermonuclear explosion. This explosion is the most energetic type of supernovae and is used as a "standard candle" for measuring distances in the universe.
torch.Size([100, 1, 32000])
MEMORY ALLOCATED:  5417919488
_________________________________________________________________

In [ ]:
print(len(inputs[0]))

2048


In [ ]:
print(len(outputs.sequences[0]))

2050


In [ ]:
print(outputs.logits)

(tensor([[-2.0000, -5.8984,  7.2109,  ..., -0.9106, -1.4121, -0.3457]],
       device='cuda:0'), tensor([[-0.4568, -0.0986, 12.2344,  ...,  1.9121, -0.3894, -1.3857]],
       device='cuda:0'), tensor([[-3.9297, -5.6094, 13.0469,  ..., -1.1797,  0.1827, -1.1279]],
       device='cuda:0'))


In [ ]:
# @title
print(diffOutputs)
responses = [tokenizer.decode(output, skip_special_tokens=True) for output in diffOutputs]
print(responses)